import { ConfigService } from '@nestjs/config';
import { DataSourceOptions } from 'typeorm';
import {
  ClassZoomMeetingEntity,
  MeetingAttendanceSegmentEntity,
  MeetingInstanceEntity,
  MeetingParticipantEntity,
  MeetingRecordingEntity,
  MeetingTeacherMetricEntity,
  MeetingTranscriptEntity,
  VideoConferenceEntity,
  ZoomUserEntity,
} from '../entities/audit.entities';
import {
  ClassGroupEntity,
  ClassGroupTeacherEntity,
  ClassMeetingEntity,
  ClassOfferingEntity,
  ClassTeacherEntity,
  CourseSectionHourRequirementEntity,
  ScheduleConflictEntity,
} from '../entities/planning.entities';
import {
  ClassSyllabusKeywordEntity,
  ClassSyllabusSessionEntity,
  MeetingSummaryEntity,
  MeetingSyllabusMatchEntity,
} from '../entities/syllabus.entities';
import {
  AcademicProgramCampusEntity,
  AcademicProgramEntity,
  BuildingEntity,
  CampusEntity,
  ClassroomSectionScheduleEntity,
  ClassroomEntity,
  ClassroomTypeEntity,
  CourseEntity,
  CourseSectionEntity,
  ExternalSessionEntity,
  ExternalSourceEntity,
  FacultyEntity,
  SectionEntity,
  SemesterEntity,
  StudyPlanEntity,
  SyncJobEntity,
  SyncLogEntity,
  TeacherEntity,
} from '../entities/catalog-sync.entities';

import {
  VideoconferenceEntity,
  VcPeriodEntity,
  VcFacultyEntity,
  VcAcademicProgramEntity,
  VcCourseEntity,
  VcSectionEntity,
} from '../videoconference/videoconference.entity';

export const appEntities = [
  VideoconferenceEntity,
  VcPeriodEntity,
  VcFacultyEntity,
  VcAcademicProgramEntity,
  VcCourseEntity,
  VcSectionEntity,
  ClassOfferingEntity,
  ClassGroupEntity,
  ClassMeetingEntity,
  ClassTeacherEntity,
  ClassGroupTeacherEntity,
  CourseSectionHourRequirementEntity,
  ScheduleConflictEntity,
  ZoomUserEntity,
  VideoConferenceEntity,
  ClassZoomMeetingEntity,
  MeetingInstanceEntity,
  MeetingParticipantEntity,
  MeetingAttendanceSegmentEntity,
  MeetingTeacherMetricEntity,
  MeetingRecordingEntity,
  MeetingTranscriptEntity,
  ClassSyllabusSessionEntity,
  ClassSyllabusKeywordEntity,
  MeetingSyllabusMatchEntity,
  MeetingSummaryEntity,
  SemesterEntity,
  CampusEntity,
  FacultyEntity,
  AcademicProgramEntity,
  StudyPlanEntity,
  SectionEntity,
  CourseEntity,
  TeacherEntity,
  ClassroomTypeEntity,
  BuildingEntity,
  ClassroomEntity,
  ClassroomSectionScheduleEntity,
  AcademicProgramCampusEntity,
  CourseSectionEntity,
  ExternalSourceEntity,
  ExternalSessionEntity,
  SyncJobEntity,
  SyncLogEntity,
];

export function buildTypeOrmConfig(configService: ConfigService): DataSourceOptions {
  return {
    type: 'mysql',
    host: configService.get<string>('DB_HOST', 'localhost'),
    port: Number(configService.get<string>('DB_PORT', '3306')),
    username: configService.get<string>('DB_USER', 'root'),
    password: configService.get<string>('DB_PASSWORD', 'root'),
    database: configService.get<string>('DB_NAME', 'uai_planning'),
    entities: appEntities,
    synchronize: configService.get<string>('DB_SYNCHRONIZE', 'true') === 'true',
    timezone: 'Z',
  };
}
