export const WINDOW_PERMISSIONS = {
  PLANNING: 'window.planning',
  CONFLICTS: 'window.conflicts',
  AUDIT: 'window.audit',
  VIDEOCONFERENCES: 'window.videoconferences',
  SECURITY: 'window.security',
  SETTINGS: 'window.settings',
} as const;

export const ACTION_PERMISSIONS = {
  USERS_MANAGE: 'action.users.manage',
  ROLES_MANAGE: 'action.roles.manage',
  PERMISSIONS_MANAGE: 'action.permissions.manage',
  SETTINGS_MANAGE: 'action.settings.manage',
  PLANNING_CHANGE_LOG_VIEW: 'action.planning.change_log.view',
  PLANNING_PLAN_SUBMIT_REVIEW: 'action.planning.plan.submit_review',
  PLANNING_PLAN_REVIEW_DECIDE: 'action.planning.plan.review_decide',
  VIDEOCONFERENCES_GENERATE: 'action.videoconferences.generate',
  VIDEOCONFERENCES_RETRY: 'action.videoconferences.retry',
  VIDEOCONFERENCES_ZOOM_CONFIG_VIEW: 'action.videoconferences.zoom_config.view',
  VIDEOCONFERENCES_MANAGEMENT_VIEW: 'action.videoconferences.management.view',
  VIDEOCONFERENCES_INHERITANCES_VIEW: 'action.videoconferences.inheritances.view',
  VIDEOCONFERENCES_AKADEMIC_COPY_VIEW: 'action.videoconferences.akademic_copy.view',
  VIDEOCONFERENCES_ZOOM_USERS_VIEW: 'action.videoconferences.zoom_users.view',
  VIDEOCONFERENCES_CURSOS_ESPECIALES_VIEW: 'action.videoconferences.cursos_especiales.view',
  VIDEOCONFERENCES_REPROGRAMACIONES_VIEW: 'action.videoconferences.reprogramaciones.view',
  AUDIT_EXPORT: 'action.audit.export',
  SYNC_EXECUTE: 'action.settings.sync_execute',
} as const;

export const ROLE_CODES = {
  ADMIN: 'ADMIN',
  ADMINISTRATIVE: 'ADMINISTRATIVE',
  IT_SUPPORT: 'IT_SUPPORT',
} as const;

export const AUTH_PUBLIC_KEY = 'auth:public';
export const AUTH_PERMISSIONS_KEY = 'auth:permissions';

export const ACCESS_TOKEN_DEFAULT_EXPIRES = '8h';
export const REFRESH_TOKEN_DEFAULT_EXPIRES_DAYS = 30;

export const DEFAULT_ADMIN_USERNAME = 'admin';
export const DEFAULT_ADMIN_PASSWORD = 'admin123';

export const PERMISSION_SEEDS = [
  {
    code: WINDOW_PERMISSIONS.PLANNING,
    type: 'WINDOW' as const,
    description: 'Acceso a la ventana de planificacion.',
    display_name: 'Planificacion',
    group_key: 'planning',
    parent_window_code: null,
    sort_order: 10,
  },
  {
    code: WINDOW_PERMISSIONS.CONFLICTS,
    type: 'WINDOW' as const,
    description: 'Acceso a la ventana de cruces.',
    display_name: 'Cruces',
    group_key: 'conflicts',
    parent_window_code: null,
    sort_order: 20,
  },
  {
    code: WINDOW_PERMISSIONS.AUDIT,
    type: 'WINDOW' as const,
    description: 'Acceso a la ventana de auditoria Zoom.',
    display_name: 'Auditoria Zoom',
    group_key: 'audit',
    parent_window_code: null,
    sort_order: 30,
  },
  {
    code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    type: 'WINDOW' as const,
    description: 'Acceso a la ventana de videoconferencias.',
    display_name: 'Videoconferencias',
    group_key: 'videoconferences',
    parent_window_code: null,
    sort_order: 40,
  },
  {
    code: WINDOW_PERMISSIONS.SECURITY,
    type: 'WINDOW' as const,
    description: 'Acceso a la ventana de seguridad.',
    display_name: 'Seguridad',
    group_key: 'security',
    parent_window_code: null,
    sort_order: 50,
  },
  {
    code: WINDOW_PERMISSIONS.SETTINGS,
    type: 'WINDOW' as const,
    description: 'Acceso a la ventana de configuracion.',
    display_name: 'Configuracion',
    group_key: 'settings',
    parent_window_code: null,
    sort_order: 60,
  },
  {
    code: ACTION_PERMISSIONS.USERS_MANAGE,
    type: 'ACTION' as const,
    description: 'Gestion de usuarios.',
    display_name: 'Gestionar usuarios',
    group_key: 'security',
    parent_window_code: WINDOW_PERMISSIONS.SECURITY,
    sort_order: 100,
  },
  {
    code: ACTION_PERMISSIONS.ROLES_MANAGE,
    type: 'ACTION' as const,
    description: 'Gestion de roles.',
    display_name: 'Gestionar roles',
    group_key: 'security',
    parent_window_code: WINDOW_PERMISSIONS.SECURITY,
    sort_order: 110,
  },
  {
    code: ACTION_PERMISSIONS.PERMISSIONS_MANAGE,
    type: 'ACTION' as const,
    description: 'Gestion de privilegios.',
    display_name: 'Gestionar privilegios',
    group_key: 'security',
    parent_window_code: WINDOW_PERMISSIONS.SECURITY,
    sort_order: 120,
  },
  {
    code: ACTION_PERMISSIONS.SETTINGS_MANAGE,
    type: 'ACTION' as const,
    description: 'Gestion operativa de configuracion.',
    display_name: 'Gestion operativa de configuracion',
    group_key: 'settings',
    parent_window_code: WINDOW_PERMISSIONS.SETTINGS,
    sort_order: 130,
  },
  {
    code: ACTION_PERMISSIONS.PLANNING_CHANGE_LOG_VIEW,
    type: 'ACTION' as const,
    description: 'Consulta del historial de cambios de planificacion manual.',
    display_name: 'Ver historial de cambios',
    group_key: 'planning',
    parent_window_code: WINDOW_PERMISSIONS.PLANNING,
    sort_order: 140,
  },
  {
    code: ACTION_PERMISSIONS.PLANNING_PLAN_SUBMIT_REVIEW,
    type: 'ACTION' as const,
    description: 'Enviar planes de planificacion a revision.',
    display_name: 'Enviar plan a revision',
    group_key: 'planning',
    parent_window_code: WINDOW_PERMISSIONS.PLANNING,
    sort_order: 150,
  },
  {
    code: ACTION_PERMISSIONS.PLANNING_PLAN_REVIEW_DECIDE,
    type: 'ACTION' as const,
    description: 'Aprobar planes o mandarlos a correccion.',
    display_name: 'Aprobar o corregir plan',
    group_key: 'planning',
    parent_window_code: WINDOW_PERMISSIONS.PLANNING,
    sort_order: 160,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_GENERATE,
    type: 'ACTION' as const,
    description: 'Generar y previsualizar videoconferencias Zoom.',
    display_name: 'Generar videoconferencias',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 170,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_RETRY,
    type: 'ACTION' as const,
    description: 'Reintentar match y acciones de correccion sobre videoconferencias.',
    display_name: 'Reintentar y corregir VC',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 180,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_ZOOM_CONFIG_VIEW,
    type: 'ACTION' as const,
    description: 'Acceso al panel de Configuracion Zoom.',
    display_name: 'Ver Configuracion Zoom',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 171,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_MANAGEMENT_VIEW,
    type: 'ACTION' as const,
    description: 'Acceso al panel de Gestion de videoconferencias.',
    display_name: 'Ver Gestion de VC',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 172,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_INHERITANCES_VIEW,
    type: 'ACTION' as const,
    description: 'Acceso al panel de Herencias Zoom.',
    display_name: 'Ver Herencias Zoom',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 173,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_AKADEMIC_COPY_VIEW,
    type: 'ACTION' as const,
    description: 'Acceso al panel de previsualizacion de copias Akademic para herencias Zoom.',
    display_name: 'Ver Copias Akademic',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 174,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_ZOOM_USERS_VIEW,
    type: 'ACTION' as const,
    description: 'Acceso al panel de Usuarios Zoom.',
    display_name: 'Ver Usuarios Zoom',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 175,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_CURSOS_ESPECIALES_VIEW,
    type: 'ACTION' as const,
    description: 'Acceso al panel de Cursos Especiales.',
    display_name: 'Ver Cursos Especiales',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 176,
  },
  {
    code: ACTION_PERMISSIONS.VIDEOCONFERENCES_REPROGRAMACIONES_VIEW,
    type: 'ACTION' as const,
    description: 'Acceso al panel de Reprogramaciones.',
    display_name: 'Ver Reprogramaciones',
    group_key: 'videoconferences',
    parent_window_code: WINDOW_PERMISSIONS.VIDEOCONFERENCES,
    sort_order: 177,
  },
  {
    code: ACTION_PERMISSIONS.AUDIT_EXPORT,
    type: 'ACTION' as const,
    description: 'Exportar datos y reportes de auditoria Zoom.',
    display_name: 'Exportar auditoria',
    group_key: 'audit',
    parent_window_code: WINDOW_PERMISSIONS.AUDIT,
    sort_order: 190,
  },
  {
    code: ACTION_PERMISSIONS.SYNC_EXECUTE,
    type: 'ACTION' as const,
    description: 'Ejecutar sincronizaciones con Akademic.',
    display_name: 'Ejecutar sincronizacion',
    group_key: 'settings',
    parent_window_code: WINDOW_PERMISSIONS.SETTINGS,
    sort_order: 200,
  },
] as const;

export const ROLE_SEEDS = [
  {
    code: ROLE_CODES.ADMIN,
    name: 'Administrador',
    permissionCodes: [...PERMISSION_SEEDS.map((item) => item.code)],
  },
  {
    code: ROLE_CODES.ADMINISTRATIVE,
    name: 'Administrativo',
    permissionCodes: [WINDOW_PERMISSIONS.PLANNING],
  },
  {
    code: ROLE_CODES.IT_SUPPORT,
    name: 'Soporte TI',
    permissionCodes: [
      WINDOW_PERMISSIONS.PLANNING,
      WINDOW_PERMISSIONS.CONFLICTS,
      WINDOW_PERMISSIONS.AUDIT,
      WINDOW_PERMISSIONS.VIDEOCONFERENCES,
      ACTION_PERMISSIONS.VIDEOCONFERENCES_ZOOM_CONFIG_VIEW,
      ACTION_PERMISSIONS.VIDEOCONFERENCES_MANAGEMENT_VIEW,
      ACTION_PERMISSIONS.VIDEOCONFERENCES_INHERITANCES_VIEW,
      ACTION_PERMISSIONS.VIDEOCONFERENCES_AKADEMIC_COPY_VIEW,
      ACTION_PERMISSIONS.VIDEOCONFERENCES_ZOOM_USERS_VIEW,
      ACTION_PERMISSIONS.VIDEOCONFERENCES_CURSOS_ESPECIALES_VIEW,
      ACTION_PERMISSIONS.VIDEOCONFERENCES_REPROGRAMACIONES_VIEW,
    ],
  },
] as const;
